name: PixelWorldProV2
main: com.mcyzj.pixelworldpro.PixelWorldPro
version: '${version}'
author: mcyzj&dong
softdepend: [ Vault, PlaceholderAPI, PlayerPoints, PixelPlayerWorld, jiangfriends, ShadowLevels]
api-version: 1.13
folia-supported: true

runtime-libraries:
  libraries-folder: '@Server:libraries'  # 存放依赖的位置
  libraries:
    gson:
      groupId: com.google.code.gson
      artifactId: gson
      version: "2.10"
    slf4j-api:
      groupId: org.slf4j
      artifactId: slf4j-api
      version: "1.7.22"
    slf4j-simple:
      groupId: org.slf4j
      artifactId: slf4j-simple
      version: "1.7.22"
    jedis:
      groupId: redis.clients
      artifactId: jedis
      version: "3.7.0"
    bcprov-lts8on:
      groupId: org.bouncycastle
      artifactId: bcprov-lts8on
      version: "2.73.3"
    commons-pool:
      groupId: org.apache.commons
      artifactId: commons-pool2
      version: "2.11.1"
    commons-compress:
      groupId: org.apache.commons
      artifactId: commons-compress
      version: "1.21"
    oshi-core:
      groupId: com.github.oshi
      artifactId: oshi-core
      version: "3.12.2"
    mysql:
      groupId: mysql
      artifactId: mysql-connector-java
      version: "5.1.6"
    kotlin:
      groupId: net.corda.kotlin
      artifactId: kotlin-stdlib-jdk8-osgi
      version: "1.7.21"
    7z:
      groupId: org.tukaani
      artifactId: xz
      version: "1.8"
